apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicshop-app
  namespace: default
  labels:
    app: musicshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicshop
  template:
    metadata:
      labels:
        app: musicshop
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: musicshop
        # ATTENZIONE: MODIFICA LA RIGA QUI SOTTO CON LA TUA IMMAGINE REALE
        image: INSERISCI_QUI_IL_LINK_ALLA_TUA_IMMAGINE:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: musicshop-config
        - secretRef:
            name: musicshop-secret
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: / 
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
